---
apiVersion: v1
kind: Service
metadata:
  name: mobile-assets
  labels:
    app: mobile-assets
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: mobile-assets
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-assets-deployment
  labels:
    app: mobile-assets
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-assets
    spec:
      containers:
        - image: dexhunter/codepattern-mobile-assets:latest
          imagePullPolicy: Always
          name: mobile-assets
          env:
            - name: MONGODB_URL
              value: 'mongodb://admin:KKPAZRVBOSFHZAYU@portal-ssl827-45.bmix-dal-yp-772887b7-c28d-474e-a854-e677f40cb390.159276422.composedb.com:19382,portal-ssl817-46.bmix-dal-yp-772887b7-c28d-474e-a854-e677f40cb390.159276422.composedb.com:19382/compose?authSource=admin&ssl=true'
          ports:
            - containerPort: 8080
